CREATE TABLE `ingExtraProperties` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `ingredient_id` int(11) NOT NULL,
    `ingredient_name` varchar(255) NOT NULL,
    `class` varchar(11) NOT NULL,
    `type2` varchar(255) DEFAULT NULL,
    `profile2` varchar(255) DEFAULT NULL,
    `fullProfile` varchar(255) NOT NULL,
    `ifraRestriction` varchar(255) DEFAULT NULL,
    `dilutionPercentiles` varchar(255) DEFAULT NULL,
    `avaiableDilutions` varchar(255) DEFAULT NULL,
    `storeInFridge` varchar(255) DEFAULT NULL,
    `tenacityOnPaper` varchar(255) DEFAULT NULL,
    `diluteNotes` varchar(255) DEFAULT NULL,
    `casEU` varchar(255) DEFAULT NULL,
    `purchaseLink` varchar(255) DEFAULT NULL,
    `moreInfo1` varchar(255) DEFAULT NULL,
    `moreInfo2` varchar(255) DEFAULT NULL,
    `moreInfo3` varchar(255) DEFAULT NULL,
    `addedByMe` varchar(255) DEFAULT NULL,
    `tags` varchar(255) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `ingredient_id` (`ingredient_id`)
) ENGINE = InnoDB AUTO_INCREMENT = 620 DEFAULT CHARSET = utf8 COLLATE = utf8_general_ci;
